// Publishes Sea drafts into the content collection.
//
// The drafts under src/plan/the-sea-that-hung-above-the-world/work/drafts stay
// the source of truth; this script copies their prose into
// src/content/the-sea-that-hung-above-the-world/chapters/<id>.md with
// generated frontmatter from sea-chapter-manifest.ts. It is idempotent: files
// are written only when their content changes, and orphans are reported but
// never deleted.
//
// Run:  pnpm sea:sync            (write changed chapters)
//       pnpm sea:sync --check    (exit 1 when any chapter is missing or stale)
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SEA_ARCS, type SeaArc } from "../../data/sea/arcs";
import { measureBody } from "../reading-time-core.mjs";
import { SEA_CHAPTER_MANIFEST, type SeaChapterManifestEntry } from "./sea-chapter-manifest";

export const SEA_CHAPTERS_DIR = "src/content/the-sea-that-hung-above-the-world/chapters";
export const GENERATED_NOTICE =
  "# GENERATED by src/scripts/sea/sync-sea-chapters.ts — edit the draft, then run pnpm sea:sync";

const HEADING_RE = /^#\s+(?:บทที่\s*(\d+)\s*:\s*(.+?)|บทนำ(?:\s*:\s*(.+))?)\s*$/;
const POV_RE = /^\*POV:\s*(.+?)\*\s*$/;
const ARC_END_RE = /^\*\s*(?:—\s*)?จบ\s+(?:อาร์กที่|Arc)\s*(\d+)\s*:\s*(.+?)\s*(?:—\s*)?\*$/;
const CHAPTER_END_RE = /^\*จบ บทที่\s*(\d+)\*$/;
const RULE_RE = /^---\s*$/;
const SCENE_RE = /^##\s/;

export interface ParsedDraft {
  number: number;
  title: string;
  pov: string | null;
  body: string;
  arcEnd: boolean;
  sceneCount: number;
  warnings: string[];
}

export interface ChapterMetrics {
  readingMinutes: number;
  wordsThai: number;
}

export function normalizeSource(source: string): string {
  return source.replace(/^﻿/, "").replace(/\r\n?/g, "\n");
}

export function parseDraft(
  source: string,
  entry: Pick<SeaChapterManifestEntry, "id" | "number" | "arc" | "expectPov" | "zoneShifts">,
  arcs: readonly SeaArc[] = SEA_ARCS,
): ParsedDraft {
  const where = `chapter ${entry.id}`;
  const lines = normalizeSource(source).split("\n");
  const warnings: string[] = [];

  let cursor = 0;
  const skipBlank = () => {
    while (cursor < lines.length && lines[cursor].trim() === "") cursor++;
  };

  skipBlank();
  const heading = HEADING_RE.exec(lines[cursor] ?? "");
  if (!heading) {
    throw new Error(`${where}: first line must be "# บทที่ N: title" or "# บทนำ", got ${JSON.stringify(lines[cursor] ?? "")}`);
  }
  const isPrologue = heading[1] === undefined;
  const number = isPrologue ? 0 : Number(heading[1]);
  const title = (isPrologue ? heading[3] ?? "บทนำ" : heading[2]).trim();
  if (number !== entry.number) {
    throw new Error(`${where}: heading says chapter ${number}, manifest expects ${entry.number}`);
  }
  cursor++;

  skipBlank();
  let pov: string | null = null;
  const povMatch = POV_RE.exec(lines[cursor] ?? "");
  if (povMatch) {
    pov = povMatch[1].trim();
    cursor++;
    skipBlank();
  }
  if (RULE_RE.test(lines[cursor] ?? "")) {
    cursor++;
  }

  const body = lines.slice(cursor);
  const arc = arcs.find((candidate) => candidate.number === entry.arc);
  let arcEnd = false;

  // Peel closing scaffolding from the end until nothing more matches.
  for (;;) {
    while (body.length > 0 && body[body.length - 1].trim() === "") body.pop();
    const last = (body[body.length - 1] ?? "").trim();

    const arcMatch = ARC_END_RE.exec(last);
    if (arcMatch) {
      const markerArc = Number(arcMatch[1]);
      if (markerArc !== entry.arc) {
        throw new Error(`${where}: arc-end marker names arc ${markerArc}, manifest puts the chapter in arc ${entry.arc}`);
      }
      const markerTitle = arcMatch[2].trim();
      if (arc && markerTitle !== arc.titleTh && markerTitle !== arc.titleEn) {
        warnings.push(`${where}: arc-end marker title "${markerTitle}" differs from arcs.ts "${arc.titleTh}"`);
      }
      arcEnd = true;
      body.pop();
      continue;
    }

    const endMatch = CHAPTER_END_RE.exec(last);
    if (endMatch) {
      if (Number(endMatch[1]) !== entry.number) {
        throw new Error(`${where}: end marker says chapter ${endMatch[1]}, manifest expects ${entry.number}`);
      }
      body.pop();
      continue;
    }

    if (RULE_RE.test(last)) {
      body.pop();
      continue;
    }

    break;
  }

  while (body.length > 0 && body[0].trim() === "") body.shift();

  body.forEach((line, index) => {
    if (/^#\s/.test(line)) {
      throw new Error(`${where}: stray top-level heading in body at line ${index + 1}: ${line}`);
    }
    if (/^\*จบ /.test(line)) {
      throw new Error(`${where}: stray end marker in body at line ${index + 1}: ${line}`);
    }
  });
  if (body.every((line) => line.trim() === "")) {
    throw new Error(`${where}: body is empty`);
  }

  const sceneCount = body.filter((line) => SCENE_RE.test(line)).length;
  for (const shift of entry.zoneShifts ?? []) {
    if (!Number.isInteger(shift.scene) || shift.scene < 1 || shift.scene > sceneCount) {
      throw new Error(`${where}: zone shift points at scene ${shift.scene}, but the draft has ${sceneCount} scene headings`);
    }
  }

  for (const name of entry.expectPov ?? []) {
    if (!pov || !pov.includes(name)) {
      warnings.push(`${where}: expected "${name}" in the POV line, got ${pov === null ? "no POV line" : JSON.stringify(pov)}`);
    }
  }

  return { number, title, pov, body: `${body.join("\n")}\n`, arcEnd, sceneCount, warnings };
}

export function measureChapter(body: string): ChapterMetrics {
  const { readingMinutes, wordsThai } = measureBody(body);
  return { readingMinutes, wordsThai };
}

const str = (value: string) => JSON.stringify(value);

export function renderChapterFile(
  entry: SeaChapterManifestEntry,
  parsed: Pick<ParsedDraft, "title" | "body" | "arcEnd">,
  metrics: ChapterMetrics,
): string {
  const lines = [
    "---",
    GENERATED_NOTICE,
    `number: ${entry.number}`,
    `arc: ${entry.arc}`,
    `title: ${str(parsed.title)}`,
    "plate:",
    `  place: ${str(entry.plate.place)}`,
    ...(entry.plate.time === undefined ? [] : [`  time: ${str(entry.plate.time)}`]),
    `  pov: ${JSON.stringify(entry.plate.pov)}`,
    `zone: ${str(entry.zone)}`,
    `zoneShifts: ${JSON.stringify((entry.zoneShifts ?? []).map(({ scene, zone }) => ({ scene, zone })))}`,
    `musicCueId: ${str(entry.musicCueId)}`,
    `readingMinutes: ${metrics.readingMinutes}`,
    `wordsThai: ${metrics.wordsThai}`,
    `arcEnd: ${parsed.arcEnd}`,
    `draft: ${entry.draft}`,
    `source: ${str(entry.source)}`,
    "---",
    "",
  ];
  return `${lines.join("\n")}\n${parsed.body}`;
}

export function validateManifest(
  manifest: readonly SeaChapterManifestEntry[],
  arcs: readonly SeaArc[] = SEA_ARCS,
): void {
  const ids = new Set<string>();
  const numbers = new Set<number>();
  for (const entry of manifest) {
    if (entry.id !== String(entry.number).padStart(2, "0")) {
      throw new Error(`manifest: id ${entry.id} does not match number ${entry.number}`);
    }
    if (ids.has(entry.id) || numbers.has(entry.number)) {
      throw new Error(`manifest: duplicate chapter ${entry.id}`);
    }
    ids.add(entry.id);
    numbers.add(entry.number);
    const arc = arcs.find((candidate) => candidate.number === entry.arc);
    if (!arc) {
      throw new Error(`manifest: chapter ${entry.id} names unknown arc ${entry.arc}`);
    }
    if (entry.number < arc.chapterStart || entry.number > arc.chapterEnd) {
      throw new Error(
        `manifest: chapter ${entry.id} is outside arc ${arc.number} (${arc.chapterStart}-${arc.chapterEnd})`,
      );
    }
  }
}

export interface SyncResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  orphans: string[];
  warnings: string[];
}

export function syncSeaChapters(root: string, { check = false } = {}): SyncResult {
  validateManifest(SEA_CHAPTER_MANIFEST);
  const outDir = join(root, SEA_CHAPTERS_DIR);
  const result: SyncResult = { created: [], updated: [], unchanged: [], orphans: [], warnings: [] };

  if (!check) {
    mkdirSync(outDir, { recursive: true });
  }

  for (const entry of SEA_CHAPTER_MANIFEST) {
    const sourcePath = join(root, entry.source);
    if (!existsSync(sourcePath)) {
      throw new Error(`chapter ${entry.id}: draft not found at ${entry.source}`);
    }
    const parsed = parseDraft(readFileSync(sourcePath, "utf8"), entry);
    result.warnings.push(...parsed.warnings);
    const rendered = renderChapterFile(entry, parsed, measureChapter(parsed.body));

    const fileName = `${entry.id}.md`;
    const outPath = join(outDir, fileName);
    // Compare with line endings normalized: a checkout with core.autocrlf=true
    // turns the generated LF files into CRLF without changing their content.
    const existing = existsSync(outPath) ? normalizeSource(readFileSync(outPath, "utf8")) : null;
    if (existing === rendered) {
      result.unchanged.push(fileName);
      continue;
    }
    (existing === null ? result.created : result.updated).push(fileName);
    if (!check) {
      writeFileSync(outPath, rendered, "utf8");
    }
  }

  if (existsSync(outDir)) {
    const expected = new Set(SEA_CHAPTER_MANIFEST.map((entry) => `${entry.id}.md`));
    result.orphans = readdirSync(outDir)
      .filter((file) => file.endsWith(".md") && !expected.has(file))
      .sort();
  }

  return result;
}

const isMain = process.argv[1] ? fileURLToPath(import.meta.url) === process.argv[1] : false;

if (isMain) {
  const check = process.argv.includes("--check");
  const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
  try {
    const result = syncSeaChapters(root, { check });
    const verb = check ? "would be " : "";
    for (const file of result.created) console.log(`${verb}created   ${SEA_CHAPTERS_DIR}/${file}`);
    for (const file of result.updated) console.log(`${verb}updated   ${SEA_CHAPTERS_DIR}/${file}`);
    for (const warning of result.warnings) console.warn(`warning: ${warning}`);
    for (const file of result.orphans) {
      console.warn(`orphan (not in manifest, left in place): ${SEA_CHAPTERS_DIR}/${file}`);
    }
    const changed = result.created.length + result.updated.length;
    console.log(
      `sea:sync${check ? " --check" : ""}: ${result.created.length} created, ${result.updated.length} updated, ${result.unchanged.length} unchanged`,
    );
    if (check && changed > 0) {
      console.error("Sea chapters are stale. Run pnpm sea:sync.");
      process.exitCode = 1;
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
